import type {Metadata} from "next";
export const metadata:Metadata={title:{absolute:"اسنوکریا | Snookeria – دنیای اسنوکر"},description:"اسنوکریا (Snookeria)؛ دنیای اسنوکر، آموزش تخصصی در آکادمی اسنوکریا، اخبار و مطالب آموزشی اسنوکر با ایمان گلشنی.",alternates:{canonical:"/"},openGraph:{title:"اسنوکریا | Snookeria",url:"/",type:"website"}};
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import HomeFeed from "@/components/discover/HomeFeed";
import type {FeedPost} from "@/components/discover/DiscoverFeed";
export const dynamic = "force-dynamic";
const brandSchema={"@context":"https://schema.org","@type":"Organization","@id":"https://snookeria.ir/#organization",name:"اسنوکریا",alternateName:"Snookeria",url:"https://snookeria.ir",logo:"https://snookeria.ir/snookeria-logo-1024.png",sameAs:["https://www.instagram.com/snookeria/","https://www.youtube.com/@snookeria"],founder:{"@id":"https://snookeria.ir/coach/iman-golshani#person"}};
export default async function Home(){const cms=createClient(process.env.NEXT_PUBLIC_CMS_SUPABASE_URL!,process.env.NEXT_PUBLIC_CMS_SUPABASE_ANON_KEY!,{auth:{persistSession:false}});const q=cms.from("posts").select("id,title,slug,excerpt,body,cover_image_url,category,post_media(id,media_url,media_type,alt_text,sort_order)").eq("status","published").order("published_at",{ascending:false}).order("id",{ascending:false}).range(0,4);const {data,error}=await q;const posts=error?(await cms.from("posts").select("id,title,slug,excerpt,body,cover_image_url,category").eq("status","published").order("published_at",{ascending:false}).order("id",{ascending:false}).range(0,4)).data??[]:data??[];return <main className="app-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(brandSchema).replace(/</g,"\\u003c")}}/><div className="mx-auto max-w-[520px] py-3 sm:px-4"><HomeFeed initialPosts={posts as FeedPost[]}/></div><section aria-label="معرفی اسنوکریا" className="mx-auto max-w-[520px] px-4 pt-8 pb-8"><h1 className="text-xl font-extrabold text-[var(--ink)]">اسنوکریا؛ دنیای اسنوکر</h1><p className="mt-2 text-sm leading-7 text-[var(--muted)]">آموزش اسنوکر، نکات فنی، قوانین و تازه‌ترین مطالب دنیای اسنوکر؛ همراه با آکادمی اسنوکریا.</p><nav aria-label="لینک‌های مهم اسنوکریا" className="mt-3 flex flex-wrap gap-2 text-xs"><Link href="/academy" className="rounded-full border border-white/15 px-3 py-2">آکادمی اسنوکریا</Link><Link href="/coach/iman-golshani" className="rounded-full border border-white/15 px-3 py-2">ایمان گلشنی؛ مربی اسنوکر</Link><Link href="/discover" className="rounded-full border border-white/15 px-3 py-2">دنیای اسنوکر</Link><a href="https://www.instagram.com/snookeria/" target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/15 px-3 py-2">اینستاگرام اسنوکریا</a><a href="https://www.youtube.com/@snookeria" target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/15 px-3 py-2">یوتیوب اسنوکریا</a></nav></section></main>}
