"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import DiscoverFeed,{type FeedPost} from "./DiscoverFeed";
import {cmsSupabase} from "@/lib/supabase/cms";
const SIZE=5;
export default function HomeFeed({initialPosts}:{initialPosts:FeedPost[]}){const[posts,setPosts]=useState(initialPosts),[loading,setLoading]=useState(false),[hasMore,setHasMore]=useState(initialPosts.length===SIZE),[error,setError]=useState(false);const loadingRef=useRef(false),offsetRef=useRef(initialPosts.length),endRef=useRef<HTMLDivElement>(null);
const loadMore=useCallback(async()=>{if(loadingRef.current||!hasMore)return;loadingRef.current=true;setLoading(true);setError(false);try{const from=offsetRef.current;let {data,error:queryError}=await cmsSupabase.from("posts").select("id,title,slug,excerpt,body,cover_image_url,category,post_media(id,media_url,media_type,alt_text,sort_order)").eq("status","published").order("published_at",{ascending:false}).order("id",{ascending:false}).range(from,from+SIZE-1);if(queryError){const fallback=await cmsSupabase.from("posts").select("id,title,slug,excerpt,body,cover_image_url,category").eq("status","published").order("published_at",{ascending:false}).order("id",{ascending:false}).range(from,from+SIZE-1);data=fallback.data as typeof data;queryError=fallback.error}if(queryError)throw queryError;const batch=(data??[]) as FeedPost[];offsetRef.current+=batch.length;setPosts(prev=>{const known=new Set(prev.map(p=>p.id));return [...prev,...batch.filter(p=>!known.has(p.id))]});setHasMore(batch.length===SIZE)}catch{setError(true)}finally{loadingRef.current=false;setLoading(false)}},[hasMore]);
useEffect(()=>{const el=endRef.current;if(!el||!hasMore)return;const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting)void loadMore()},{rootMargin:"400px"});observer.observe(el);return()=>observer.disconnect()},[loadMore,hasMore]);
return <><DiscoverFeed posts={posts}/>{posts.length===0&&<p className="py-16 text-center text-sm text-[var(--muted)]">هنوز مطلبی منتشر نشده است.</p>}<div ref={endRef} className="min-h-8 text-center text-xs text-[var(--muted)]">{loading?"در حال بارگذاری...":error?<button onClick={()=>void loadMore()} className="py-4 text-[var(--accent)]">تلاش دوباره</button>:null}</div></>}
