"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {BookOpen,Eye,FileText,LogOut,MessageCircle,Plus,Target,Users,Wrench,ArrowLeft,ExternalLink,Images,Layers3,CalendarDays,ChevronLeft,Sparkles} from "lucide-react";
import {cmsSupabase} from "@/lib/supabase/cms";
type Counts={posts:number;published:number;shots:number;workshops:number;registrations:number};
const sections=[
 {title:"مطالب و دیسکاور",detail:"ساخت پست، مدیریت اسلایدها، انتشار و سئو",href:"/admin/posts",icon:Images,tag:"CONTENT",color:"text-rose-400",background:"bg-rose-500/10",featured:true},
 {title:"دسته‌بندی‌ها",detail:"مدیریت موضوعات، تصویر و ترتیب نمایش",href:"/admin/categories",icon:Layers3,tag:"CATEGORIES",color:"text-sky-400",background:"bg-sky-500/10"},
 {title:"جمله روز",detail:"انتشار و مدیریت Snookeria Says",href:"/admin/says",icon:MessageCircle,tag:"SAYS",color:"text-violet-400",background:"bg-violet-500/10"},
 {title:"ضربه روز",detail:"مدیریت محتوای Shot of the Day",href:"/admin/shots",icon:Target,tag:"SHOTS",color:"text-emerald-400",background:"bg-emerald-500/10"},
 {title:"کارگاه‌ها",detail:"دوره‌ها، ظرفیت‌ها و ثبت‌نام‌ها",href:"/admin/workshops",icon:Wrench,tag:"WORKSHOPS",color:"text-amber-400",background:"bg-amber-500/10"}
];
export default function AdminPage(){
 const router=useRouter();const[ready,setReady]=useState(false);
 const[counts,setCounts]=useState<Counts>({posts:0,published:0,shots:0,workshops:0,registrations:0});
 useEffect(()=>{let mounted=true;(async()=>{const{data}=await cmsSupabase.auth.getSession();if(!data.session){router.replace("/admin/login");return}const[p,pub,s,w,reg]=await Promise.all([cmsSupabase.from("posts").select("*",{count:"exact",head:true}),cmsSupabase.from("posts").select("*",{count:"exact",head:true}).eq("status","published"),cmsSupabase.from("shots_of_the_day").select("*",{count:"exact",head:true}),cmsSupabase.from("workshops").select("*",{count:"exact",head:true}),cmsSupabase.from("workshop_registrations").select("*",{count:"exact",head:true})]);if(mounted){setCounts({posts:p.count??0,published:pub.count??0,shots:s.count??0,workshops:w.count??0,registrations:reg.count??0});setReady(true)}})();return()=>{mounted=false}},[router]);
 async function logout(){await cmsSupabase.auth.signOut();router.replace("/admin/login")}
 const stats=[{label:"کل مطالب",value:counts.posts,icon:FileText},{label:"منتشرشده",value:counts.published,icon:Eye},{label:"پیش‌نویس",value:Math.max(0,counts.posts-counts.published),icon:BookOpen},{label:"ثبت‌نام‌ها",value:counts.registrations,icon:Users}];
 return <main dir="rtl" className="min-h-screen bg-[var(--page)] pb-20 text-[var(--ink)]">
  <header className="sticky top-0 z-40 border-b border-[var(--edge)] bg-[var(--page)]/95 px-4 py-3 backdrop-blur-xl sm:px-7"><div className="mx-auto flex max-w-6xl items-center justify-between">
   <div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[var(--accent)] text-white"><Sparkles size={22}/></div><div><p className="text-[10px] font-bold tracking-[.16em] text-[var(--accent)]">SNOOKERIA STUDIO</p><h1 className="text-lg font-black">پنل مدیریت اسنوکریا</h1></div></div>
   <div className="flex gap-2"><Link href="/" aria-label="مشاهده سایت" className="flex h-10 w-10 items-center justify-center rounded-xl border border-[var(--edge)] bg-[var(--surface)]"><ExternalLink size={17}/></Link><button onClick={logout} aria-label="خروج" className="flex h-10 w-10 items-center justify-center rounded-xl border border-[var(--edge)] bg-[var(--surface)] text-[var(--muted)]"><LogOut size={17}/></button></div>
  </div></header>
  <div className="mx-auto max-w-6xl space-y-7 px-4 py-6 sm:px-7">
   <section className="relative overflow-hidden rounded-3xl border border-[var(--edge)] bg-[var(--surface)] p-5 shadow-[var(--shadow)] sm:p-7"><div className="pointer-events-none absolute -left-12 -top-16 h-52 w-52 rounded-full bg-[var(--accent)] opacity-[.08] blur-3xl"/><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-[11px] font-bold text-[var(--accent)]">فضای مدیریت محتوا</p><h2 className="mt-2 text-xl font-black sm:text-2xl">امروز چه محتوایی منتشر می‌کنیم؟</h2><p className="mt-2 text-xs leading-6 text-[var(--muted)]">مطالب، تصاویر و بخش‌های مختلف اسنوکریا را از همین‌جا مدیریت کن.</p></div><Link href="/admin/posts" className="inline-flex h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-[var(--accent)] px-5 text-sm font-bold text-white"><Plus size={18}/> مدیریت و ساخت مطلب <ArrowLeft size={17}/></Link></div></section>
   <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(({label,value,icon:Icon})=><div key={label} className="rounded-2xl border border-[var(--edge)] bg-[var(--surface)] p-4 shadow-sm sm:p-5"><div className="flex items-center justify-between"><span className="text-[11px] text-[var(--muted)]">{label}</span><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><Icon size={17}/></span></div><p className="mt-4 text-3xl font-black tabular-nums">{ready?value.toLocaleString("fa-IR"):"—"}</p></div>)}</section>
   <section><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-bold tracking-widest text-[var(--accent)]">CONTENT MANAGEMENT</p><h2 className="mt-1 text-lg font-black">مدیریت محتوا</h2></div><span className="rounded-full border border-[var(--edge)] px-3 py-1 text-[11px] text-[var(--muted)]">۵ بخش</span></div>
    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{sections.map(({title,detail,href,icon:Icon,tag,color,background,featured})=><Link key={href} href={href} className={`group relative flex min-h-48 flex-col justify-between overflow-hidden rounded-3xl border border-[var(--edge)] bg-[var(--surface)] p-5 shadow-sm transition-all duration-200 hover:-translate-y-1 hover:border-[var(--accent)] hover:shadow-lg active:scale-[.99] ${featured?"md:col-span-2 lg:col-span-2":""}`}><div className="flex items-start justify-between"><span className={`flex h-13 w-13 items-center justify-center rounded-2xl p-3 ${background} ${color}`}><Icon size={26}/></span><span className="text-[10px] font-bold tracking-widest text-[var(--muted)]">{tag}</span></div><div className="mt-6 flex items-end justify-between gap-4"><div><h3 className="text-base font-black sm:text-lg">{title}</h3><p className="mt-2 max-w-sm text-xs leading-6 text-[var(--muted)]">{detail}</p></div><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-[var(--edge)] bg-[var(--surface-raised)] transition group-hover:bg-[var(--accent)] group-hover:text-white"><ChevronLeft size={18}/></span></div></Link>)}</div>
   </section>
   <section className="flex items-center justify-between rounded-2xl border border-[var(--edge)] bg-[var(--surface)] p-4"><div className="flex items-center gap-3"><CalendarDays size={18} className="text-[var(--accent)]"/><span className="text-sm font-bold">کارگاه‌های ثبت‌شده</span></div><strong className="text-xl">{ready?counts.workshops.toLocaleString("fa-IR"):"—"}</strong></section>
  </div>
 </main>
}
