"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {BookOpen,Eye,FileText,LogOut,MessageCircle,Plus,Target,Users,Wrench,ArrowLeft,ExternalLink} from "lucide-react";
import {cmsSupabase} from "@/lib/supabase/cms";
type Counts={posts:number;published:number;shots:number;workshops:number;registrations:number};
const links=[{title:"مطالب و دیسکاور",detail:"مقاله، تصویر و ویدئو",href:"/admin/posts",icon:BookOpen},{title:"جمله روز",detail:"Snookeria Says",href:"/admin/says",icon:MessageCircle},{title:"ضربه روز",detail:"Shot of the Day",href:"/admin/shots",icon:Target},{title:"کارگاه‌ها",detail:"دوره‌ها و ثبت‌نام‌ها",href:"/admin/workshops",icon:Wrench}];
export default function AdminPage(){const router=useRouter();const[ready,setReady]=useState(false);const[counts,setCounts]=useState<Counts>({posts:0,published:0,shots:0,workshops:0,registrations:0});
useEffect(()=>{let mounted=true;(async()=>{const{data}=await cmsSupabase.auth.getSession();if(!data.session){router.replace("/admin/login");return}const[p,pub,s,w,reg]=await Promise.all([cmsSupabase.from("posts").select("*",{count:"exact",head:true}),cmsSupabase.from("posts").select("*",{count:"exact",head:true}).eq("status","published"),cmsSupabase.from("shots_of_the_day").select("*",{count:"exact",head:true}),cmsSupabase.from("workshops").select("*",{count:"exact",head:true}),cmsSupabase.from("workshop_registrations").select("*",{count:"exact",head:true})]);if(mounted){setCounts({posts:p.count??0,published:pub.count??0,shots:s.count??0,workshops:w.count??0,registrations:reg.count??0});setReady(true)}})();return()=>{mounted=false}},[router]);
async function logout(){await cmsSupabase.auth.signOut();router.replace("/admin/login")}
const stats=[{label:"کل مطالب",value:counts.posts,icon:FileText},{label:"منتشرشده",value:counts.published,icon:Eye},{label:"پیش‌نویس",value:Math.max(0,counts.posts-counts.published),icon:BookOpen},{label:"ثبت‌نام‌ها",value:counts.registrations,icon:Users}];
return <main dir="rtl" className="min-h-screen bg-[var(--page)] pb-24 text-[var(--ink)]"><div className="mx-auto max-w-[720px] px-4 pb-10 pt-5">
<header className="flex items-center justify-between"><div><p className="text-[11px] font-bold text-[var(--accent)]">SNOOKERIA STUDIO</p><h1 className="mt-1 text-[24px] font-black">مدیریت اسنوکریا</h1></div><div className="flex gap-2"><Link href="/" aria-label="مشاهده سایت" className="flex h-10 w-10 items-center justify-center rounded-xl border border-[var(--edge)] bg-[var(--surface)]"><ExternalLink size={17}/></Link><button onClick={logout} aria-label="خروج" className="flex h-10 w-10 items-center justify-center rounded-xl border border-[var(--edge)] bg-[var(--surface)] text-[var(--muted)]"><LogOut size={17}/></button></div></header>
<Link href="/admin/posts" className="mt-7 flex items-center justify-between rounded-2xl bg-[var(--accent)] px-5 py-4 text-white shadow-[var(--shadow)]"><span className="flex items-center gap-3"><Plus size={21}/><span className="text-sm font-bold">ساخت مطلب جدید</span></span><ArrowLeft size={19}/></Link>
<section className="mt-6 grid grid-cols-2 gap-3">{stats.map(({label,value,icon:Icon})=><div key={label} className="rounded-2xl border border-[var(--edge)] bg-[var(--surface)] p-4 shadow-[var(--shadow)]"><div className="flex items-center justify-between text-[var(--muted)]"><span className="text-[11px]">{label}</span><Icon size={17}/></div><p className="mt-4 text-2xl font-black tabular-nums">{value.toLocaleString("fa-IR")}</p></div>)}</section>
<section className="mt-8"><h2 className="mb-3 text-sm font-black">مدیریت محتوا</h2><div className="grid gap-3 sm:grid-cols-2">{links.map(({title,detail,href,icon:Icon})=><Link key={href} href={href} className="flex items-center gap-3 rounded-2xl border border-[var(--edge)] bg-[var(--surface)] p-4 shadow-[var(--shadow)] transition active:scale-[.99]"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><Icon size={20}/></div><div className="min-w-0 flex-1"><h3 className="text-[13px] font-bold">{title}</h3><p className="mt-1 text-[11px] text-[var(--muted)]">{detail}</p></div><ArrowLeft size={16} className="text-[var(--muted)]"/></Link>)}</div></section>
<section className="mt-6 flex items-center justify-between rounded-2xl border border-[var(--edge)] bg-[var(--surface)] p-4"><span className="text-xs text-[var(--muted)]">کارگاه‌های ثبت‌شده</span><strong className="text-lg">{counts.workshops.toLocaleString("fa-IR")}</strong></section>
</div></main>}
