"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {cmsSupabase} from "@/lib/supabase/cms";
type Category={slug:string;name:string;image_url:string|null;sort_order:number;is_active:boolean};
export default function CategoriesAdmin(){
 const router=useRouter();const [items,setItems]=useState<Category[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [slug,setSlug]=useState(""),[name,setName]=useState(""),[image,setImage]=useState(""),[uploading,setUploading]=useState(false);
 async function reload(){const {data,error:e}=await cmsSupabase.from("post_categories").select("slug,name,image_url,sort_order,is_active").order("sort_order");if(e)setError("ابتدا فایل SQL دسته‌بندی‌ها را در Supabase اجرا کن: "+e.message);else {setItems(data??[]);setError("")}}
 useEffect(()=>{void (async()=>{const {data}=await cmsSupabase.auth.getSession();if(!data.session){router.replace("/admin/login");return}await reload();setReady(true)})()},[router]);
 async function uploadCover(file:File, categorySlug?:string){if(!file.type.startsWith("image/")){setError("فقط فایل تصویری انتخاب کن.");return}if(file.size>5*1024*1024){setError("حجم تصویر باید کمتر از ۵ مگابایت باشد.");return}setUploading(true);setError("");const ext=(file.name.split(".").pop()||"png").toLowerCase();const path=`categories/${crypto.randomUUID()}.${ext}`;const {error:e}=await cmsSupabase.storage.from("cms-media").upload(path,file,{contentType:file.type,upsert:false});if(e){setError("آپلود تصویر انجام نشد: "+e.message)}else{const {data}=cmsSupabase.storage.from("cms-media").getPublicUrl(path);if(categorySlug){const {error:saveError}=await cmsSupabase.from("post_categories").update({image_url:data.publicUrl}).eq("slug",categorySlug);if(saveError)setError(saveError.message);else await reload()}else setImage(data.publicUrl)}setUploading(false)}
 async function add(){if(!name.trim()||!/^[a-z0-9][a-z0-9_-]*$/.test(slug)){setError("نام فارسی و شناسه انگلیسی معتبر وارد کن.");return}setBusy(true);const {error:e}=await cmsSupabase.from("post_categories").insert({slug,name:name.trim(),image_url:image.trim()||null,sort_order:100});setBusy(false);if(e)setError(e.message);else {setSlug("");setName("");setImage("");await reload()}}
 async function change(item:Category,patch:Partial<Category>){const {error:e}=await cmsSupabase.from("post_categories").update(patch).eq("slug",item.slug);if(e)setError(e.message);else await reload()}
 if(!ready)return <main className="min-h-screen bg-[var(--page)]"/>;
 return <main dir="rtl" className="min-h-screen bg-[var(--page)] px-4 py-7 text-white"><div className="mx-auto max-w-2xl"><Link href="/admin" className="text-xs text-red-400">بازگشت به مدیریت</Link><h1 className="mt-4 text-2xl font-black">دسته‌بندی مطالب</h1><p className="mt-2 text-xs leading-6 text-[var(--muted)]">شناسه انگلیسی پس از ساخت ثابت می‌ماند. ترتیب دسته‌بندی‌ها در صفحه اصلی بر اساس آخرین مطلب منتشرشده به‌صورت خودکار تعیین می‌شود.</p>
 {error&&<p className="mt-4 rounded-xl bg-red-500/10 p-3 text-xs text-red-300">{error}</p>}
 <section className="mt-6 space-y-3 rounded-2xl border border-white/10 bg-white/[.03] p-4"><h2 className="font-bold">دسته‌بندی جدید</h2><input className="w-full rounded-xl bg-white/10 p-3 text-sm" placeholder="نام فارسی، مثلاً قوانین اسنوکر" value={name} onChange={e=>setName(e.target.value)}/><input dir="ltr" className="w-full rounded-xl bg-white/10 p-3 text-sm" placeholder="slug: rules" value={slug} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9_-]/g,""))}/><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-white/20 p-3 text-xs"><span className="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-full bg-white/10">{image?<img src={image} alt="پیش‌نمایش کاور" className="h-full w-full object-cover"/>:"＋"}</span><span>{uploading?"در حال آپلود...":"انتخاب عکس کاور دسته‌بندی (مربع، حداکثر ۵ مگابایت)"}</span><input type="file" accept="image/*" className="hidden" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadCover(file);e.target.value=""}}/></label><button disabled={busy||uploading} onClick={add} className="rounded-xl bg-red-600 px-5 py-3 text-sm font-bold disabled:opacity-50">افزودن دسته‌بندی</button></section>
 <section className="mt-6 space-y-3">{items.map(item=><div key={item.slug} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.03] p-3">{item.image_url?<img src={item.image_url} alt="" className="h-12 w-12 rounded-full object-cover"/>:<div className="flex h-12 w-12 items-center justify-center rounded-full bg-red-600/20 text-lg">●</div>}<div className="min-w-0 flex-1"><div className="font-bold">{item.name}</div><div dir="ltr" className="text-right text-xs text-white/40">{item.slug}</div></div><button onClick={()=>{const v=window.prompt("نام دسته‌بندی",item.name);if(v?.trim())void change(item,{name:v.trim()})}} className="rounded-lg bg-white/10 px-2 py-2 text-xs">ویرایش</button><button onClick={()=>void change(item,{is_active:!item.is_active})} className="rounded-lg bg-white/10 px-2 py-2 text-xs">{item.is_active?"فعال":"غیرفعال"}</button><label className="cursor-pointer rounded-lg bg-white/10 px-2 py-2 text-xs">عکس<input type="file" accept="image/*" disabled={uploading} className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadCover(file,item.slug);e.target.value=""}}/></label></div>)}</section></div></main>
}